FROM apache/airflow:3.0.2-python3.11

USER root
RUN apt-get update && apt-get install -y \
    libpq-dev gcc \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt /
RUN pip install --upgrade pip setuptools && \
    pip install -r /requirements.txt
